name: Dokka for Github Pages

# This workflow will:
#  1. Trigger on a push to the `main` branch.
#  2. Check out the repository.
#  3. Set up JDK 19.
#  4. Build the project using Gradle.
#  5. Generate Dokka HTML documentation.
#  6. Move the generated documentation to the `/docs` directory.
#  7. Commit and push the changes to the `main` branch, updating GitHub Pages.

on:
  push:
    branches:
      - main

jobs:
  dokka:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Generate Dokka HTML
        run: ./gradlew dokkaHtml

      - name: Move Dokka HTML to docs
        run: |
          rm -rf docs
          mkdir -p docs
          mv lib/build/dokka/html/* docs/

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs
          git commit -m 'Update Dokka documentation'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}